// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vcacvrgxvbtyzatxctki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjYWN2cmd4dmJ0eXphdHhjdGtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NTM4NzMsImV4cCI6MjA5MzIyOTg3M30.oA111WXKu4cKuh7m5Z0d8Fn_IOF0X23qlrwCi1e0epk";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);